apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: final-project
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: custom-gp2   # لازم يكون نفس اسم الـ StorageClass
  resources:
    requests:
      storage: 5Gi
